apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-back-app
  template:
    metadata:
      labels:
        app: spring-back-app
    spec:
      containers:
        - name: spring-container
          image: armcool004/spring_backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  type: LoadBalancer
  selector:
    app: spring-back-app
  ports:
    - port: 80
      targetPort: 8080


